### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by iambateman** [erlandmuchasaj/laravel-modules#1]
This is really cool, thanks for sharing what you're making! 

### Tests
Your code looked really good, but I didn't see tests. I would definitely want to see some tests ship with the package for something this low-level. https://laravelpackage.com/04-testing.html#installing-phpunit

### Config
it looks like your config includes `composer` with your personal information in it, which I would find confusing.

### Overall purpose
Having spent a few minutes looking at what you're doing, I think I understand. It looks like you can create separate "sections" of functionality within a single repository. So if I had a "user management" section and a "recipe creator" both within one application that were substantially different from one another, I could separate them into modules. Let me know if I got that right.

I think I'd like to see a sample video explaining what it does and why. It wasn't immediately obvious to me what I should expect it to do.

**Comment by erlandmuchasaj** [comment]
Hello, @iambateman thank you for the feedback.

### Overall purpose

First, let me explain the overall purpose of the package. 
Basically, the main goal of the package is to separate the logic into different "Domains" which basically are "Modules".
For example, for a large-scale project, you might have different entities such as User, Roles, Permissions, Login History, Activities, Products, Orders, Invoices, Subscriptions, Files, etc. 

So what you want is that Groupe common entities into one module, For example
Module **User** can have different models such as _User, Role, Permission, LoginHistory_, 
Module **Core** can have models such as Activity, Announcements, and Setting, so logic is more generic and can be used by other modules as well.
You can have a Module **Subscription** that handles everything related to the subscription.

So a module is an encapsulation of related model entities and this way different developers can work in different modules. 

### Config

For the composer can you point to which information are you referring, because I can refactor it and remove it if necessary.

### Tests 

For the tests, you are right the package itself has not have any tests yet, but it can generate tests when you are creating a module with the command: `php artisan module:make-test Core 'TestCaseName'`

**Comment by erlandmuchasaj** [comment]
> This is really cool, thanks for sharing what you're making!
> 
> ### Tests
> Your code looked really good, but I didn't see tests. I would definitely want to see some tests ship with the package for something this low-level. https://laravelpackage.com/04-testing.html#installing-phpunit
> 
> ### Config
> it looks like your config includes `composer` with your personal information in it, which I would find confusing.
> 
> ### Overall purpose
> Having spent a few minutes looking at what you're doing, I think I understand. It looks like you can create separate "sections" of functionality within a single repository. So if I had a "user management" section and a "recipe creator" both within one application that were substantially different from one another, I could separate them into modules. Let me know if I got that right.
> 
> I think I'd like to see a sample video explaining what it does and why. It wasn't immediately obvious to me what I should expect it to do.
